export const CustId = 'CustId'
export const saveId = 'saveId'
export const SelectProduct = 'SelectProduct'
export const selectedProduct = 'selectedProduct'
export const SaveString = 'SaveString'
export const searchString = 'searchString'